// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Allow overriding with DATABASE_URL; fall back to a local sqlite file for quick testing
    url: process.env["DATABASE_URL"] || `file:./dev.db`,
  },
});
